from .inverted_residual import InvertedResidual
from .plane import PlaneResidual,PlaneResidual_no_lastBN
from .bottleneck import BottleneckResidual,BottleneckResidual_no_lastBN
from .inception import InceptionA,InceptionB,InceptionC,InceptionD